name: Build and Upload to CDN
on:
  push:
    branches:
      - master
jobs:
  build-and-upload:
    env:
      CDN_URL: ${{ secrets.CDN_URL }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - uses: pnpm/action-setup@v4
        with:
          version: 8.6.3
      - run: pnpm i
      - run: pnpm run build && rm dist/ssr-manifest.json
      - name: Upload to COS
        uses: zkqiang/tencent-cos-action@v0.1.0
        with:
          args: upload -r ./dist/ homepage
          secret_id: ${{ secrets.COS_SECRET_ID }}
          secret_key: ${{ secrets.COS_SECRET_KEY }}
          bucket: ${{ secrets.COS_BUCKET }}
          region: ${{ secrets.COS_REGION }}
